README.Rmd
README.md

the CRAN badge and the install from Github links still pointed to dplyr

two stray dplyr->dbplyr changes

---

R/dbi-s3.r
tests/testthat/test-tbl-sql.r

Second try, this time with test case

quoting table names for db_write_table and test case

---

vignettes/dbplyr.Rmd

A few typo / grammatical fixes to the dbplyr intro vignette. Edits are only in the narrative, not the code.

Minor typo / grammatical fixes to vignette

---

NEWS.md
R/translate-sql-base.r
tests/testthat/test-translate.r

Translate magrittr pipe

---

R/dbi-s3.r

Fixes tidyverse/dplyr#2907. Closes rstats-db/RSQLite#220.

Avoid warning from compute()

---

NEWS.md
R/db-sqlite.r
tests/testthat/test-translate-sqlite.R

Transalte na_if to NULLIF rather than NULL_IF when using a SQLite
connection.

Fix na_if Translation for SQLite

---

R/src_dbi.R
R/tbl-lazy.R

Call setOldClass() on S3 classes

---

R/sql-build.R
R/tbl-lazy.R
R/utils.r
tests/testthat/test-mutate.r

- closes tidyverse/dplyr#3216
- closes tidyverse/dplyr#3222
- closes tidyverse/dplyr#3223

Maintain variable order in mutate()

---

vignettes/dbplyr.Rmd

Is this the best place to submit a modification?  Or should I do it on the dbplyr repo? https://github.com/rstudio/db.rstudio.com/blob/master/content/dplyr.Rmd

further distinguish the location of the execution

---

man/join.tbl_sql.Rd

Fixes https://github.com/tidyverse/dplyr/issues/3600

Fixes #3600

---

R/sql-query.R

I haven't found any usage of `get_join_xy_names()`.

Remove dead code

---

DESCRIPTION
NEWS.md
R/sql-render.R

@hadley 
Related to https://github.com/rstudio/sparklyr/issues/1299

add missing con argument in sql_render.op()

---

vignettes/new-backend.Rmd

The typo is confusing for newcomers.

src_translate_env -> sql_translate_env

---

tests/testthat/test-utils.R

Increases coverage of `utils.r` to 100%

Adds test for utils.r

---

tests/testthat/test-sql-query-select.txt
tests/testthat/test-sql-query.R
tests/testthat/test-sql-translator.txt
tests/testthat/test-sql-variant.txt
tests/testthat/test-translate-sql-helpers.r
tests/testthat/test-translate-window.R

Added as many tests I could during my flight, it'll hopefully helps us with our coverage levels.

Adds 4 tests

---

vignettes/dbplyr.Rmd

RMySQL --> RMariaDB, clean RPostgreSQL reference

---

tests/testthat/test-verb-mutate.R

which doesn't have a boolean data type.

Make test compatible with MSSQL

---

R/verb-copy-to.R

Use as.data.frame() instead of overriding class

---

tests/testthat/sql/postgres-explain.sql
tests/testthat/test-backend-postgres.R

Relax output test

---

NEWS.md
R/backend-mssql.R
tests/testthat/test-backend-mssql.R

This adds preliminary support for lubridate functions for SQL Server (re: #261 ).

preliminary support for lubridate for SQL Server

---

.github/workflows/test-coverage.yaml

Install binary packages for covr

---

.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml

Embrace R 4.0 in GHA

---

R/backend-mssql.R

Add class to message about creation of table

---

NEWS.md
R/query-semi-join.R
tests/testthat/sql/join-on.sql
tests/testthat/test-query-join.R

Support sql_on for semi joins

---

tests/testthat/sql/arrange-join.txt
tests/testthat/sql/arrange-semi-join.txt
tests/testthat/sql/arrange-setop.txt
tests/testthat/sql/arrange-single.txt
tests/testthat/sql/arrange.txt
tests/testthat/test-verb-select.R

Add tests for queries generated by arrange()

---

R/zzz.R

Simplify conditioning and fix class names

---

NEWS.md
R/backend-access.R
R/backend-mssql.R
R/backend-oracle.R
R/backend-teradata.R
R/explain.R
R/query-select.R
R/sql-build.R
R/translate-sql-clause.R
man/sql_build.Rd
tests/testthat/_snaps/backend-mssql.md
tests/testthat/_snaps/verb-select.md
tests/testthat/test-backend-mssql.R
tests/testthat/test-verb-arrange.R
tests/testthat/test-verb-filter.R

Omit ORDER BY in subqueries

---

NEWS.md
R/verb-distinct.R
tests/testthat/test-verb-distinct.R

fix distinct for groups

---

NEWS.md
R/backend-mysql.R
R/backend-postgres.R

fix partial match

---

NEWS.md
R/backend-postgres-old.R
tests/testthat/test-backend-postgres-old.R

RPostgreSQL can't create temporary tables

---

NEWS.md
R/partial-eval.R
tests/testthat/_snaps/partial-eval.md
tests/testthat/test-partial-eval.R

Fixes #590 and #591 .
@hadley Basically just some copy-paste from your implementation in `dtplyr`

add support for if_any/if_all

---

NEWS.md
R/verb-group_by.R
tests/testthat/test-verb-group_by.R

Group by ungroups for empty dots

---

NEWS.md
R/backend-.R
R/backend-mssql.R
R/translate-sql-conditional.R
tests/testthat/test-translate-sql.R

support `missing` argument in `if_else()`

---

R/backend-mssql.R
tests/testthat/test-backend-mssql.R

Fix `mssql_sql_if()`: use `cond` instead of `con`

---

NEWS.md
R/db-sql.R
tests/testthat/_snaps/verb-joins.md

Fix `sql_expr_matches.DBIConnection()`

---

R/verb-summarise.R
tests/testthat/_snaps/verb-summarise.md
tests/testthat/test-verb-summarise.R

Closes #710. I left out a NEWS bullet as this seemed pretty minor but if you want I'll add one.

Better error message in `summarise()`

---

NEWS.md
R/partial-eval.R
tests/testthat/_snaps/partial-eval.md
tests/testthat/test-partial-eval.R

Default arguments for `if_any()` and `if_all()`

---

vignettes/translation-verb.Rmd

The generated SQL is now minimal, so the note doesn't really fit there anymore. I am not sure whether you want to put the note somewhere else.

Minor vignette enhancements

---

R/db.R
man/db-misc.Rd
vignettes/backend-2.Rmd

Judging from the context, these seem to be typos.

fix typo, dplyr -> dbplyr

---

NEWS.md
R/backend-mssql.R
tests/testthat/_snaps/verb-count.md
tests/testthat/test-backend-mssql.R

Fix `quantile()` translation for MS SQL

---

R/translate-sql-cut.R
R/verb-expand.R
R/verb-filter.R
R/verb-joins.R
R/verb-pivot-longer.R
R/verb-pivot-wider.R
tests/testthat/_snaps/translate-sql-cut.md
tests/testthat/_snaps/verb-expand.md
tests/testthat/_snaps/verb-filter.md
tests/testthat/_snaps/verb-joins.md
tests/testthat/_snaps/verb-pivot-longer.md
tests/testthat/_snaps/verb-pivot-wider.md

Slightly improved error messages.

Better error messages

---

R/db-sql.R
R/rows.R
man/db-sql.Rd

Fix tidyselect warning

---

NEWS.md
R/remote.R
R/verb-compute.R
man/collapse.tbl_sql.Rd
man/memdb_frame.Rd
man/remote_name.Rd

Add argument `cte` to `compute()` and `collect()`

---

NEWS.md

Add NEWS about `SELECT *`

---

R/rows.R
man/rows-db.Rd

Add more detail to rows_insert() docs

---

NEWS.md
R/translate-sql-helpers.R
R/translate-sql-quantile.R
R/translate-sql-window.R
tests/testthat/_snaps/tidyeval-across.md
tests/testthat/_snaps/translate-sql-window.md
tests/testthat/test-translate-sql-helpers.R
tests/testthat/test-translate-sql-quantile.R
tests/testthat/test-translate-sql-window.R
tests/testthat/test-translate-sql.R

Warn about na.rm = TRUE less often

---

NEWS.md
R/tbl-lazy.R
R/verb-window.R
tests/testthat/_snaps/verb-window.md
tests/testthat/test-verb-window.R

Improve error message for `window_order()` on df

---

NEWS.md
R/tidyeval.R
R/verb-mutate.R
R/verb-summarise.R
tests/testthat/_snaps/tidyeval-across.md
tests/testthat/test-tidyeval-across.R

Error on named `across()`

---

R/verb-joins.R
tests/testthat/_snaps/query-join.md
tests/testthat/test-verb-joins.R

Fixes an issue introduced in #892.

Use `LHS` and `RHS` if `sql_on` is used

---

R/lazy-join-query.R
R/verb-joins.R
R/verb-select.R
man/sql_build.Rd
tests/testthat/test-verb-joins.R
tests/testthat/test-verb-select.R

Another preparation part of #975.

Refactor semi join

---

R/verb-joins.R
tests/testthat/_snaps/verb-joins.md
tests/testthat/test-verb-joins.R

I split the PR #975 into multiple smaller PRs to make it easier to review.

Refactor `check_join_as()`

---

R/verb-select.R
tests/testthat/test-verb-summarise.R

Fix `summarise()` after `select()`

---

NEWS.md
R/backend-sqlite.R
tests/testthat/_snaps/backend-sqlite.md
tests/testthat/test-backend-sqlite.R

`quantile()` not supported for SQLite

---

DESCRIPTION
R/backend-oracle.R
R/testthat.R
tests/testthat/_snaps/backend-mssql.md
tests/testthat/_snaps/backend-mysql.md
tests/testthat/_snaps/backend-oracle.md
tests/testthat/_snaps/lazy-join-query.md
tests/testthat/_snaps/tidyeval-across.md
tests/testthat/_snaps/verb-pivot-wider.md
tests/testthat/_snaps/verb-pull.md
tests/testthat/_snaps/verb-select.md
tests/testthat/_snaps/verb-slice.md
tests/testthat/test-backend-mssql.R
tests/testthat/test-backend-mysql.R
tests/testthat/test-backend-oracle.R
tests/testthat/test-tbl-lazy.R
tests/testthat/test-verb-arrange.R
tests/testthat/test-verb-compute.R
tests/testthat/test-verb-do.R
tests/testthat/test-verb-filter.R
tests/testthat/test-verb-joins.R
tests/testthat/test-verb-mutate.R
tests/testthat/test-verb-select.R

Basic compatibility with dev dplyr, tidyselect, and vctrs

dplyr compat

---

R/rows.R
R/tidyeval-across.R
R/verb-fill.R
R/verb-group_by.R
R/verb-pull.R
R/verb-select.R
tests/testthat/_snaps/verb-select.md
tests/testthat/_snaps/verb-summarise.md

No longer needed with the new tidyselect

Remove `fix_call()`

---

R/lazy-join-query.R
R/verb-joins.R
man/sql_build.Rd
tests/testthat/test-verb-joins.R

Refactor for multi join preparation

---

NEWS.md
R/verb-filter.R
R/verb-mutate.R
R/verb-slice.R
R/verb-summarise.R
man/dbplyr-slice.Rd
man/filter.tbl_lazy.Rd
man/mutate.tbl_lazy.Rd
man/summarise.tbl_lazy.Rd
tests/testthat/_snaps/verb-filter.md
tests/testthat/_snaps/verb-mutate.md
tests/testthat/_snaps/verb-slice.md
tests/testthat/_snaps/verb-summarise.md
tests/testthat/test-verb-filter.R
tests/testthat/test-verb-mutate.R
tests/testthat/test-verb-slice.R
tests/testthat/test-verb-summarise.R

Implement `.by`

---

.github/workflows/mssql.yaml
.github/workflows/postgres.yaml
DESCRIPTION
NEWS.md
R/verb-fill.R
man/complete.tbl_lazy.Rd
man/expand.tbl_lazy.Rd
man/fill.tbl_lazy.Rd
man/pivot_longer.tbl_lazy.Rd
man/pivot_wider.tbl_lazy.Rd
man/replace_na.tbl_lazy.Rd
tests/testthat/_snaps/verb-fill.md
tests/testthat/test-verb-fill.R

`fill()` supports `"updown"`/`"downup"` and ordering by non-numeric columns

---

NEWS.md
R/backend-.R
tests/testthat/test-translate-sql-window.R

Fix `last()` without window frame

---

NEWS.md
R/backend-mssql.R
tests/testthat/test-backend-mssql.R

Improve median() translation for SQL server

---

NEWS.md
R/backend-hana.R
tests/testthat/_snaps/backend-hana.md

Improve translation for as.character() in HANA

---

NEWS.md
R/backend-mssql.R
R/db-escape.R
tests/testthat/test-backend-mssql.R
tests/testthat/test-db-escape.R

Correct "NA" translation for BLOBs

---

NEWS.md
R/verb-joins.R
tests/testthat/_snaps/verb-joins.md
tests/testthat/test-verb-joins.R

Fix 4 table join issue with renaming

---

NEWS.md
R/verb-mutate.R
tests/testthat/test-verb-mutate.R

Fix window function after `summarise()` + `select()`

---

NEWS.md
R/verb-mutate.R
tests/testthat/_snaps/verb-mutate.md
tests/testthat/test-verb-mutate.R

Don't inline `mutate()` ater `distinct()`

---

NEWS.md
R/translate-sql-window.R
tests/testthat/test-translate-sql-window.R

Fix rank functions applied to `desc(<var>)`

---

NEWS.md
R/backend-mssql.R
R/backend-postgres.R
R/translate-sql-helpers.R
man/sql_variant.Rd
tests/testthat/_snaps/backend-mssql.md
tests/testthat/_snaps/backend-postgres.md
tests/testthat/_snaps/backend-sqlite.md
tests/testthat/test-backend-mssql.R
tests/testthat/test-backend-postgres.R

Error when `quantile()` can't be translated

---

NEWS.md
R/optimise-utils.R
R/verb-filter.R
tests/testthat/test-verb-filter.R

Don't inline `filter` after windowed `mutate()`

---

NEWS.md
R/rows.R
tests/testthat/_snaps/backend-postgres.md
tests/testthat/test-backend-postgres.R

Fix `rows_*()` with Postgres and schema

---

NEWS.md
R/verb-select.R
tests/testthat/_snaps/verb-select.md
tests/testthat/test-verb-select.R

Don't always inline `select()` after `distinct()`

---

NEWS.md
R/verb-pull.R
man/pull.tbl_sql.Rd
tests/testthat/_snaps/verb-pull.md
tests/testthat/test-verb-pull.R

Add argument `name` to `pull()`

---

NEWS.md
R/translate-sql-window.R
tests/testthat/_snaps/translate-sql-window.md
tests/testthat/test-translate-sql-window.R

Support multiple variables in rank functions

---

tests/testthat/test-rows.R

Fix test for upcoming RSQLite 2.3.0

---

NEWS.md
R/translate-sql.R
tests/testthat/test-translate-sql.R

Evaluate inputs to `sql()` locally

---

R/verb-slice.R
man/dbplyr-slice.Rd
tests/testthat/_snaps/verb-slice.md
tests/testthat/test-verb-slice.R

Raise error for `slice_min/max(na_rm = FALSE)`

---

NEWS.md
R/db-sql.R
R/lazy-join-query.R
R/query-join.R
R/verb-joins.R
man/sql_build.Rd
tests/testthat/_snaps/lazy-join-query.md
tests/testthat/_snaps/verb-joins.md
tests/testthat/test-lazy-join-query.R
tests/testthat/test-verb-joins.R

Respect `na_matches` for `semi/anti_join()`

---

R/db-sql.R

To fix the CRAN check results.

Fix method consistency for `sql_select.DBIConnection()`

---

R/backend-hana.R
R/backend-mssql.R
R/backend-mysql.R
R/backend-odbc.R
R/backend-oracle.R
R/backend-postgres.R
R/backend-sqlite.R
R/db-io.R
R/db-sql.R
R/db.R
R/query-join.R
R/sql-build.R
R/tbl-sql.R
R/verb-copy-to.R
man/db-io.Rd
man/db-misc.Rd
man/db-sql.Rd

Check dots used

---

NEWS.md
R/db-io.R

Pass dots in `db_copy_to()` to `db_write_table()`

---

NEWS.md
R/verb-pivot-wider.R
tests/testthat/test-verb-pivot-wider.R

Make pivot_wider NA column name handling match tidyr

---

NEWS.md
R/tidyeval-across.R
R/tidyeval.R
tests/testthat/_snaps/tidyeval-across.md
tests/testthat/test-tidyeval-across.R

Wrap translation of `if_any/all()` in parentheses

---

NEWS.md
R/backend-.R
R/verb-distinct.R
tests/testthat/test-backend-.R

Translate `nzchar()`

---

NEWS.md
R/backend-mssql.R
tests/testthat/_snaps/backend-mssql.md

MS SQL logical not translation

---

NEWS.md
R/backend-mssql.R
tests/testthat/test-backend-mssql.R

Implement any and all for MSSQL

---

NEWS.md
R/backend-oracle.R
R/sql-clause.R
tests/testthat/_snaps/backend-oracle.md

Fix `sql_query_upsert()` for Oracle

---

NEWS.md
R/verb-slice.R
tests/testthat/_snaps/verb-slice.md
tests/testthat/test-verb-slice.R

Support data masking pronouns in `slice_*()`

---

R/backend-mssql.R
R/backend-teradata.R
R/db-sql.R
R/translate-sql-conditional.R
R/translate-sql-helpers.R
R/translate-sql-window.R
tests/testthat/test-tbl-sql.R

Step towards deprecating `build_sql()`

Avoid using `build_sql()`

---

NEWS.md
R/tidyeval.R
R/translate-sql-window.R
R/verb-arrange.R
R/verb-fill.R
R/verb-slice.R
tests/testthat/_snaps/translate-sql-window.md
tests/testthat/_snaps/verb-slice.md
tests/testthat/test-verb-slice.R

Order by multiple variables in `slice_min/max()`

---

NEWS.md
R/backend-.R
R/backend-postgres.R
R/backend-snowflake.R
R/translate-sql-string.R
tests/testthat/test-backend-postgres.R
tests/testthat/test-translate-sql-string.R

Translation for `str_detect()` and `str_starts()`

---

R/backend-snowflake.R
R/translate-sql-conditional.R
tests/testthat/test-backend-.R

Fix `glue_sql2()` uses

---

tests/testthat/test-escape.R

Fix CRAN tz issues

---

.github/workflows/R-CMD-check.yaml

Skip old R versions on Windows

---

R/db-io.R
R/db-sql.R
R/rows.R
R/verb-compute.R

Fixes #1378
@mgirlich if you use `tryCatch()` in these cases, it messes up the call tree in a way that makes debugging hard.

Use withCallingHandlers()

---

DESCRIPTION
tests/testthat/test-verb-filter.R
tests/testthat/test-verb-group_by.R
tests/testthat/test-verb-mutate.R
tests/testthat/test-verb-pivot-wider.R

For me, this takes run time down from ~30s to ~11s.

Enable parallel testing

---

R/db-io.R
R/db-sql.R
R/tidyeval-across.R
R/tidyeval.R
R/utils-check.R
R/verb-compute.R
R/verb-pivot-wider.R
man/collapse.tbl_sql.Rd

And fix doc typo that was breaking syntax highlighting.

Standardize on `withCallingHandlers` and use the same style everywhere

---

NEWS.md
R/backend-mssql.R
tests/testthat/_snaps/backend-mssql.md
tests/testthat/test-backend-mssql.R

Clear error when using windowed n_distinct() on SQL server

---

NEWS.md
R/db.R

Pass on ... in `db_sql_render()`

---

NEWS.md
R/rows.R
tests/testthat/_snaps/rows.md
tests/testthat/test-rows.R

Fix bug in `rows_patch.tbl_lazy()` throwing an error when multiple columns need to be patched

---

R/backend-oracle.R
man/backend-oracle.Rd

Add note about logical support on Oracle
