- R/tbl-lazy.R
I'm pretty sure you closed dplyr #2700 in error so dove a little bit deeper.
This looks like a pretty clear typo to me. I  know that that the underscore functions are deprecated, but this will allow me to  support both 0.5 and 0.6 more easily.
Thanks!
> Fix typo in arrange_.tbl_lazy, fixes dplyr#2700

- NEWS.md
- R/db-odbc-hive.R
- R/db-odbc-mssql.R
- R/db-odbc-oracle.R
- R/db-odbc-postgres.R
- R/db-postgres.r
- R/translate-sql-odbc.R
- tests/testthat/test-translate-odbc.R
Adds sd() scalar, aggregate and window support for MSSQL, Oracle, Hive, Impala and Postgres (for both odbc and RPostgreSQL).  It also includes some further code tidying.  Addresses `dplyr` issue https://github.com/tidyverse/dplyr/issues/2887
```
> tbl(con, "iris") %>%
+   group_by(Species) %>%
+   mutate(A_sd = sd(Sepal.Length))
```
```
Sepal.Length Sepal.Width Petal.Length Petal.Width Species      A_sd
<dbl>       <dbl>        <dbl>       <dbl>   <chr>     <dbl>
1          5.1         3.5          1.4         0.2  setosa 0.3524897
2          4.9         3.0          1.4         0.2  setosa 0.3524897
3          4.7         3.2          1.3         0.2  setosa 0.3524897
```
> Adds sd() support for 5 datasources

- vignettes/dbplyr.Rmd
Added links to "Securing Credentials" on db.rstudio.com. 
Changed links to PostgreSQL docs from v9.3 to "current".
> URLs to Securing Credentials and PostgreSQL docs

- R/translate-sql-odbc.R
Fix an error for OdbcConnection:
```r
> library(dplyr)
> library(dbplyr)
> library(odbc)
> con <- dbConnect(odbc(), dsn = "test")
> con
<OdbcConnection>  Database: test
> db_desc(con)
Error in paste0(":", port) : object 'port' not found
```
> Fix error: object 'port' not found

- NEWS.md
- R/db-odbc-mssql.R
- R/translate-sql-window.r
- man/dbplyr-package.Rd
- tests/testthat/test-translate-mssql.r
The new solution uses `~` for SELECT clauses and `NOT` for WHERE clauses.  It uses the `sql_currentcontext()` function to switch between the two.  
Here are the tests that worked: 
```
db_mtcars %>%
mutate(x = !is.na(mpg))
db_mtcars %>%
arrange(!is.na(mpg))
db_mtcars %>%
group_by(!is.na(mpg))  %>%
tally()
db_mtcars %>%
filter(!is.na(mpg))
db_mtcars %>%
filter(am != 0)
db_mtcars %>%
filter(!am == 0)
db_mtcars %>%
filter(!mpg < 30 )
db_mtcars %>%
filter(!mpg < 30 | !cyl < 8 )
db_mtcars %>%
filter(!mpg >= 30 )
db_mtcars %>%
filter(!mpg == 21 )
db_mtcars %>%
filter(mpg != 21 )
```
These didn't 
```
db_mtcars %>%
mutate(x = am != 0) %>%
show_query()
db_mtcars %>%
mutate(x = (am == 0)) %>%
show_query()
```
> Fix negated is na

- R/db-odbc-mssql.R
- tests/testthat/test-translate-mssql.r
Changes exclusive to MS SQL
- Adds custom a custom `mssql_is_na()` function that equates `cond` to TRUE so that CASE/WHEN works properly.  Because the options are binary, the False/No test is simplified to use ELSE
- Add custom to `if`, `ifelse` and `if_else` 
- Add tests 
Used same tests as https://github.com/tidyverse/dbplyr/pull/51 to confirm nothing originally fixed broke, and also tested these sucesfully:
```
db_mtcars %>%
group_by(x = ifelse(mpg < 20, "good", "bad")) %>%
select(mpg, x)
db_mtcars %>%
group_by(x = if_else(mpg < 20, "good", "bad")) %>%
select(mpg, x)
db_mtcars %>%
mutate(x = ifelse(mpg <= 20 & am == 0, "good", "bad"))
```
> Fixes ifelse after is.na eval change

- R/db-odbc-teradata.R
- tests/testthat/test-translate-teradata.r
- Fixes Teradata translation issue for `!=` operators, it now translates to `<>`. Reported by @weixing777.
- Adds a test for the change
> Teradata not equal fix

- NEWS.md
- R/db-postgres.r
- tests/testthat/test-translate-postgresql.R
Fixes https://github.com/tidyverse/dplyr/issues/3339
- It overrides `substr` in the PostgreSQL translation. It now uses `substring` which will work both in PostgreSQL and Redshift
> Switches to substring and adds test

- NEWS.md
- R/translate-sql-base.r
- tests/testthat/test-translate.r
Fixes https://github.com/tidyverse/dplyr/issues/3397
Notes:
- Tested it against an Oracle and SQLite connections
- Re-tested the MS SQL custom translation and found that it needed no changes
> Fixes instr order for default translation

- DESCRIPTION
This fixes #136. 
There was still a link to report bug to dplyr issue board instead of dbplyr one. 
I think the fix in DESCRIPTION will also fix the package documentation
https://github.com/tidyverse/dbplyr/blob/79d2a0377561ad57f67a65b914ce3195d10de0be/man/dbplyr-package.Rd#L18
There is still the website to update, but I believe it is a separate process with another timeframe, so I did not PR anything on this.
> Fix link to dbplyr own issue board

- vignettes/dbplyr.Rmd
The name of the parameter that describes the path to the database is `dbname` [1]. Unrecognized keys are ignored. If no dbname is received, an in-memory database is created by default, so the example worked anyway. Fixing this usage avoids misleading users trying to build on this example.
[1] https://github.com/r-dbi/RSQLite/blob/33d3631f2809df4eb2ab01460ef3ce73788e1488/R/connect.R#L46
> Fix parameter name in vignette

- NEWS.md
- R/translate-sql-base.r
- tests/testthat/test-translate.r
Before the PR we have the following translation
```
dbplyr::translate_sql(col %in% !!c())
<SQL> "col" IN ()
```
which isn't valid SQL. With this PR this is simply translated to FALSE
```
dbplyr::translate_sql(col %in% !!c())
<SQL> FALSE
```
Closes tidyverse/dplyr#3375.
> fix sql translation of %in% with empty vectors

- NEWS.md
- R/backend-.R
- R/translate-sql-helpers.R
This fixes #181, I wonder though whether more of `translate-sql` functions should be similarly updated.
> Remove toupper() from sql_prefix()

- R/memdb.R
- R/test-frame.R
- tests/testthat/test-lazy-ops.R
- tests/testthat/test-sql-render.R
- tests/testthat/test-verb-joins.R
- tests/testthat/test-verb-select.R
Replaces `data_frame()` for `tibble()`. See tidyverse/dplyr#4069. Completed for tidyverse developer day.
> removes data_frame() in favor of tibble()

- NEWS.md
- R/query-join.R
- R/verb-joins.R
- man/join.tbl_sql.Rd
- tests/testthat/sql/join-on.sql
- tests/testthat/test-query-join.R
- tests/testthat/test-verb-joins.R
Proposing a syntax to pass arbitrary join predicates, e.g. for working with spatial data on the database. Needs a test.
``` r
library(tidyverse)
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql
tbl1 <- memdb_frame(a = 1:3, b = 4:2)
tbl2 <- memdb_frame(c = 1:3, b = 2:0)
tbl12 <- left_join(tbl1, tbl2, by = sql("TBL_LEFT.b < TBL_RIGHT.c"))
tbl12 %>% sql_render()
#> <SQL> SELECT `TBL_LEFT`.`a` AS `a`, `TBL_LEFT`.`b` AS `b.x`, `TBL_RIGHT`.`c` AS `c`, `TBL_RIGHT`.`b` AS `b.y`
#>   FROM `ygyjgeeqdc` AS `TBL_LEFT`
#>   LEFT JOIN `urhwkxzyib` AS `TBL_RIGHT`
#>   ON (TBL_LEFT.b < TBL_RIGHT.c)
tbl12
#> # Source:   lazy query [?? x 4]
#> # Database: sqlite 3.22.0 [:memory:]
#>       a   b.x     c   b.y
#>   <int> <int> …
```
> Generic joins

- R/query-select.R
- tests/testthat/test-query-select.R
Only found a contrived example, still might be useful.
``` r
library(tidyverse)
lazy_frame(a = 1:3) %>%
mutate(b = a + 1) %>%
distinct() %>%
arrange()
#> <SQL>
#> SELECT *
#> FROM (SELECT DISTINCT *
#> FROM (SELECT `a`, `a` + 1.0 AS `b`
#> FROM `df`) `dbplyr_001`) `dbplyr_002`
```
<sup>Created on 2019-04-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
``` r
library(tidyverse)
lazy_frame(a = 1:3) %>%
mutate(b = a + 1) %>%
distinct() %>%
arrange()
#> <SQL>
#> SELECT DISTINCT `a`, `a` + 1.0 AS `b`
#> FROM `df`
```
<sup>Created on 2019-04-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
> Better squashing of trivial subqueries

- R/backend-postgres.R
- tests/testthat/sql/postgres-explain.sql
- tests/testthat/test-backend-postgres.R
What's a good place to add tests, also for other data sources?
> Fix explain() for Postgres data sources

- R/backend-mssql.R
A regression.
The partial `NextMethod()` calls didn't work for me, only when the full list of arguments is specified.
> Fix copy_to() for MSSQL databases

- R/backend-postgres.R
- tests/testthat/test-backend-postgres.R
This adds support for the lubridate `yday()` function to the PostgreSQL backend.
> add support for yday and quarter to PostgreSQL backend

- NEWS.md
- R/backend-hive.R
This comes from a question on [community.rstudio.com](https://community.rstudio.com/t/error-using-dbplyr-1-4-with-row-number/29779/5)
In dbplyr 1.3.0
```r
library(dplyr)
tab <- tbl_lazy(iris, src = simulate_hive())
query <- tab %>%
group_by(Species) %>%
filter(row_number() == 1L)
query %>% show_query()
<SQL> SELECT `Sepal.Length`, `Sepal.Width`, `Petal.Length`, `Petal.Width`, `Species`
FROM (SELECT `Sepal.Length`, `Sepal.Width`, `Petal.Length`, `Petal.Width`, `Species`, row_number() OVER (PARTITION BY `Species`) AS `zzz1`
FROM `df`) `ohjggmqvbj`
WHERE (`zzz1` = 1)
```
With 1.4.0
```r
tab <- tbl_lazy(iris, src = simulate_hive())
query <- tab %>%
group_by(Species) %>%
filter(row_number() == 1L)
query %>% show_query()
<SQL>
SELECT *
FROM `df`
WHERE (row_number() = 1)
```
A …
> Hive translations for window functions were no more working

- DESCRIPTION
- NEWS.md
- R/build-sql.R
- R/data-lahman.R
- R/data-nycflights13.R
- R/partial-eval.R
- R/utils.R
- R/verb-arrange.R
- man/arrange.tbl_lazy.Rd
- man/build_sql.Rd
- man/lahman.Rd
- man/named_commas.Rd
- man/nycflights13.Rd
- man/partial_eval.Rd
- vignettes/dbplyr.Rmd
- vignettes/notes/_postgres-setup.Rmd
- vignettes/sql.Rmd
- vignettes/translation-function.Rmd
- vignettes/translation-verb.Rmd
This fixes some typos. I renamed "mysql", "postgresql" and "sqlite" to "MySQL", "PostgreSQL" and "SQLite" where appropriate. I hope that's okay. 
While reviewing, I was wondering whether [this line](https://github.com/tidyverse/dbplyr/blob/2f17ed749e4f634c64cf1f99f1a9634f7d4378a5/vignettes/dbplyr.Rmd#L200) in the comparison of PostgreSQL with SQLite is still appropriate in its current wording, given that SQLite now supports window functions.
> Fix typos in NEWS, vignettes, documentation

- NEWS.md
- R/backend-mssql.R
- R/query-select.R
- tests/testthat/test-backend-mssql.R
> Use TOP 100 PERCENT as stop-gap to allow subqueries with ORDER BY

- tests/testthat/test-tbl-sql.R
The tests expected a simple character vector, and https://github.com/tidyverse/dplyr/pull/4399 proposes that `tbl_vars()` returns a structured object of class `dplyr_sel_vars` with the `groups` attribute set to host the grouping columns. 
This just adapts the test to unstructure the object.
> Adapt tests to changes in dplyr::tbl_vars()

- NEWS.md
- R/backend-postgres.R
- tests/testthat/test-backend-postgres.R
corrected str_detect so it is possible to use regular expressions, introduced str_replace and corrected str_replace_all with 'g' parameter
fixes #362
> postgres backend: str_detect, str_replace and str_replace_all

- R/backend-mysql.R
It doesn't look like `build_sql()` ever added spaces?
> Fix SQL for ANALYZE TABLE for MariaDB

- R/tbl-sql.R
For performance when creating multiple `tbl` objects.
This also addresses #369, should we expose `vars` in `tbl.src_dbi()`?
> Undeprecate tbl_sql(vars = )

- R/src_dbi.R
- man/tbl.src_dbi.Rd
We need to make this easier discoverable from `?tbl` too.
Closes #432.
> Tweak ?tbl.src_dbi

- vignettes/backend-2.Rmd
I only found this typo after copy/pasting things from https://dbplyr.tidyverse.org/articles/backend-2.html to sparklyr source code (because sparklyr needs to be up-to-date with all the changes from `dbplyr` edition 2). Let's get this typo corrected so that other backend authors won't need to go through the same trouble.
Signed-off-by: Yitao Li <yitao@rstudio.com>
> fixing a typo ('dbQuoteIdentifer' -> 'dbQuoteIdentifier')

- vignettes/backend-2.Rmd
It looks like `dbplyr::sql_translation()` is supposed to replace `dplyr::sql_translate_env()` eventually (or at least that's what I'm empirically observing so far while attempting to fully transition `spark_connection`s of `sparklyr` to the `dbplyr` edition 2 API)
Signed-off-by: Yitao Li <yitao@rstudio.com>
> mention `dplyr::sql_translate_env()` -> `dbplyr::sql_translation()` (?)

- R/verb-slice.R
- tests/testthat/_snaps/verb-slice.md
fixed typo in slice error message: suppoted -> supported
> typo in verb-slice.R

- NEWS.md
- R/partial-eval.R
- tests/testthat/_snaps/partial-eval.md
- tests/testthat/test-partial-eval.R
Now handles `across()` using NSE approach that's more in keeping with the keeping with the rest of dbplyr's translation, so that functions without native translation are passed along. It also gains support for `.fns = NULL` and for translating functions.
Fixes #525. Fixes #534. Fixes #554.
> Radically improved across() implementation

- NEWS.md
- R/verb-pivot-wider.R
- R/verb-summarise.R
- man/summarise.tbl_lazy.Rd
- tests/testthat/_snaps/verb-summarise.md
- tests/testthat/test-verb-summarise.R
closes #584 
I am not sure about the environment check in `summarise_verbose()`.
> support argument `.groups` in `summarise()`

- R/escape.R
I hit this error while building a shiny app running on a lazy_tbl:
```
ERROR: Cannot translate shiny inputs to SQL.
* Force evaluation in R with (e.g.) `!!inputs$x` or `local(inputs$x)`
```
When I tried the proposed solution, it did not work. This is because the object is called `input$x` not `inputs$x`
> Fix typo in shiny object name

- NEWS.md
- R/partial-eval.R
- tests/testthat/test-partial-eval.R
> Allow `stringr::` and `lubridate::` prefix

- NEWS.md
- R/explain.R
- R/remote.R
- man/complete.tbl_lazy.Rd
- man/expand.tbl_lazy.Rd
- man/fill.tbl_lazy.Rd
- man/pivot_longer.tbl_lazy.Rd
- man/pivot_wider.tbl_lazy.Rd
- man/remote_name.Rd
- man/replace_na.tbl_lazy.Rd
- tests/testthat/_snaps/backend-postgres.md
- tests/testthat/test-backend-postgres.R
> `explain()` passes `...` to methods

- R/verb-pivot-wider.R
- man/pivot_wider.tbl_lazy.Rd
Users are confused that `pivot_wider()` is not lazy (e.g. #598, #703). Collecting is only necessary to generate the spec.
As long as `tidyr::pivot_wider_spec()` is not made a generic I see two ways of handling this:
* just update the documentation (like it is done here) or
* export `dbplyr_pivot_wider_spec()` (which is lazy) so people can generate the spec locally.
@hadley Do you have any preference?
> Update `pivot_wider()` documentation

- NEWS.md
- R/verb-mutate.R
- R/verb-select.R
- man/mutate.tbl_lazy.Rd
- tests/testthat/_snaps/verb-mutate.md
- tests/testthat/test-verb-mutate.R
Fixes #670.
This PR replaces `nest_vars()` by a function that returns a list of layers. Unlike in #671 the order of variables is not changed. I still think it might be worth doing so, but then in a different PR.
Thanks to the layers most of the code to support `.keep`, `.before`, and `.after` could be copied from `dplyr`.
> Support `.keep`, `.before`, and `.after` in `mutate()`

- R/backend-mysql.R
- R/verb-copy-to.R
Adding it "after the fact" is very painful. Even if the generic isn't exported yet, adding it now makes sure we don't forget to add it later.
Should we scout for other generics that don't have an ellipsis yet?
> Add ellipsis to generic

- NEWS.md
- R/backend-oracle.R
- tests/testthat/test-backend-oracle.R
> Fix `as.Date()` translation for Oracle

- R/verb-group_by.R
- tests/testthat/_snaps/verb-group_by.md
- tests/testthat/test-verb-group_by.R
Fixes #818.
The new error message is
```r
lazy_frame(x = 1) %>% 
group_by(y)
#> Error in `group_by.tbl_lazy()`:
#> ! Must group by variables found in `.data`.
#> x Column `y` is not found
```
> Improve error message in `group_by()`

- R/translate-sql.R
- man/translate_sql.Rd
- tests/testthat/_snaps/translate-sql.md
- tests/testthat/test-translate-sql.R
- vignettes/sql.Rmd
- vignettes/translation-function.Rmd
This started out as a simple fix for #782, but then I discovered:
* The `translate_sql()` docs were rather out of date, and should mostly just point to `vignette("function-translation")`
* That vignette would also be a more appropriate place to mention `dplyr.strict_sql`.
* The current error in strict mode wasn't very informative and could easily be made better.
* `vignette("SQL")` went into way too much detail about what happens when functions couldn't be translated, and that would also be more appropriate `vignette("function-translation")`.
> Improve function translation docs

- R/backend-oracle.R
- R/backend-sqlite.R
- R/db-sql.R
- R/query-join.R
- R/verb-joins.R
This helps #748: without this change, updating dm to be compatible with the new `rows_*()` implementation will be hard.
> Avoid sql_escape_ident() in sql_table_prefix()

- R/db-sql.R
- tests/testthat/_snaps/backend-mysql.md
- tests/testthat/test-backend-mysql.R
Remove extra spaces in rendered SQL, test with two rows.
> Tweak copy_inline() for MySQL

- R/backend-oracle.R
- R/backend-sqlite.R
- R/db-sql.R
- man/db-sql.Rd
- tests/testthat/_snaps/backend-.md
`unique_subquery_name()` is private, do we really want to expose it?
> Use name = NULL default for sql_query_wrap()

- DESCRIPTION
- NEWS.md
- R/backend-hive.R
- R/db-sql.R
- R/escape.R
- R/explain.R
- R/sql-build.R
- R/sql-clause.R
- R/utils-format.R
- tests/testthat/_snaps/verb-select.md
- tests/testthat/test-verb-select.R
Closes #644.
It uses a global option to avoid having to add an argument `colour` to lots of functions (as proposed by Hadley https://github.com/tidyverse/dbplyr/issues/644#issuecomment-1095590348). Probably, this misses some places but I like how simple this was to add.
> Highlight keywords in `show_query()`

- R/lazy-query.R
- tests/testthat/_snaps/translate-sql-window.md
- tests/testthat/test-translate-sql-window.R
It checks that `frame` is finite but this is not necessarily the case. There was no test yet but I stumbled over it when working on support for `HAVING`.
> Fix too strict check of `frame` in `lazy_query()`

- R/data-lahman.R
- R/data-nycflights13.R
Since these are called primarily for their side-effects they should return their first argument invisibly. Fixes #862
> Make example data generators return invisibly

- R/src_dbi.R
Fixes #889.
It still makes sense to use `tbl_src_dbi()` to make sure the `vars` argument is provided but we should keep the dispatch via `tbl()`.
> Use `tbl()` in `tbl_src_dbi()`

- NEWS.md
- R/db-sql.R
- dbplyr.Rproj
> Fix `semi/anti_join()` for Spark

- R/verb-compute.R
- tests/testthat/test-verb-compute.R
> `compute()` can handle schema

- NEWS.md
- R/backend-.R
- R/translate-sql.R
- tests/testthat/test-translate-sql.R
Fixes #952.
``` r
library(dplyr, warn.conflicts = FALSE)
lazy_frame(x = 1) %>% 
mutate(x = sql(paste0("x")))
#> <SQL>
#> SELECT CONCAT_WS('', 'x') AS `x`
#> FROM `df`
#> <SQL>
#> SELECT x AS `x`
#> FROM `df`
```
> Evaluate `sql()` locally

- NEWS.md
- R/explain.R
- R/utils-format.R
- tests/testthat/test-verb-select.R
Fixes #974.
It would be even nicer if we could detect a dark theme ourselves but cli does not export `detect_dark_theme()`.
Where should this be documented so that users can easily find it?
> Add option to control keyword highlighting

- NEWS.md
- R/sql-build.R
- tests/testthat/_snaps/verb-joins.md
- tests/testthat/test-verb-joins.R
Fixes #978. The logic was already used for `select_query`. It seems I simply forgot to use it for joins and set op queries.
> Reuse query for joins and set ops

- NEWS.md
- R/backend-mysql.R
- R/backend-postgres.R
- R/backend-redshift.R
- R/backend-snowflake.R
- tests/testthat/test-test-backend-snowflake.R
Adds `collapse = ''` as the default for `str_flatten` for postgres, snowflake, redshift, and mysql.  This is the behavior of `stringr::str_flatten`.
> Add default value for collapse arg for str_flatten

- NEWS.md
- R/backend-snowflake.R
- tests/testthat/test-test-backend-snowflake.R
Surrounds `pattern` with parentheses for `snowflake_grepl`, due to `.*` on either end.  Fixes patterns like `'a|b'`, which should match `'cabbage'` but do not (translates to `REGEXP ('.*' || ('a|b') || '.*)` instead of `REGEXP ('.*' || '(a|b)' || '.*')`
> Add parentheses to snowflake grepl pattern

- .github/ISSUE_TEMPLATE/issue_template.md
I was trying to debug something with dbplyr and thought: _wouldn't it be great if packages like dbplyr included small examples that could be used for reprexes?_ And I was thrilled to see that dbplyr has exactly this kind of article!
This PR modifies the issue template to link out to that article to increase the likelihood that someone with an issue will find it.
> Link to _Reprexes for dbplyr_ in issue template

- DESCRIPTION
- NEWS.md
- R/optimise-utils.R
- tests/testthat/_snaps/escape.md
- tests/testthat/_snaps/verb-expand.md
- tests/testthat/_snaps/verb-pivot-longer.md
- tests/testthat/_snaps/verb-pivot-wider.md
Using `map()` on calls has been deprecated.
> Wrap call as list before applying `map()`

- DESCRIPTION
- R/lazy-join-query.R
- R/lazy-select-query.R
- R/verb-arrange.R
- R/verb-distinct.R
- R/verb-filter.R
- R/verb-head.R
- R/verb-select.R
- R/verb-set-ops.R
- R/verb-summarise.R
- man/sql_build.Rd
- tests/testthat/_snaps/lazy-select-query.md
- tests/testthat/_snaps/verb-arrange.md
- tests/testthat/test-lazy-select-query.R
- tests/testthat/test-verb-filter.R
- tests/testthat/test-verb-summarise.R
The field `last_op` was introduced when switching to the lazy query structure but it was only meant as a temporary helper for optimisations. With some minor modifications it isn't needed anymore. It is a breaking change but I don't expect other packages to actually break.
`revdepcheck()` confirms that there are no new problems.
> Remove field `last_op`

- R/lazy-select-query.R
- R/verb-mutate.R
- R/verb-select.R
- R/verb-summarise.R
The logic in `add_select()` mixed `mutate()` and `select()` and was therefore more complicated than it actually had to be.
> Refactor `add_select()`

- DESCRIPTION
- R/verb-pivot-longer.R
- R/verb-pivot-wider.R
Closes #1090. Wait for release of tidyr 1.3.0 https://github.com/tidyverse/tidyr/issues/1455.
> Use `error_call` arg from `build_*_spec()`

- NEWS.md
- R/verb-pivot-longer.R
- R/verb-pivot-wider.R
- man/pivot_longer.tbl_lazy.Rd
- man/pivot_wider.tbl_lazy.Rd
- tests/testthat/_snaps/verb-mutate.md
- tests/testthat/_snaps/verb-pivot-longer.md
- tests/testthat/_snaps/verb-pivot-wider.md
- tests/testthat/test-verb-pivot-longer.R
- tests/testthat/test-verb-pivot-wider.R
Move dots, add unsupported arguments `cols_vary` and `id_expand` for better error messages.
> `pivot_*()` upkeep

- NEWS.md
- R/verb-joins.R
- man/join.tbl_sql.Rd
To make the argument order more consistent to the data frame join methods. This is a breaking change but it should be quite minor.
> Move argument `auto_index` after dots in `*_join()`

- NEWS.md
- R/verb-filter.R
- tests/testthat/_snaps/verb-filter.md
- tests/testthat/test-verb-filter.R
> Can use `filter(f(<x>))` on a summarised variable

- NEWS.md
- R/tidyeval-across.R
- tests/testthat/_snaps/tidyeval-across.md
- tests/testthat/_snaps/verb-select.md
- tests/testthat/test-tidyeval-across.R
- tests/testthat/test-verb-select.R
> Error when using predicates in `across()`

- R/utils.R
- tests/testthat/helper-src.R
- tests/testthat/test-backend-mssql.R
- tests/testthat/test-backend-mysql.R
- tests/testthat/test-backend-postgres-old.R
- tests/testthat/test-backend-postgres.R
- tests/testthat/test-db-io.R
- tests/testthat/test-db-sql.R
- tests/testthat/test-rows.R
- tests/testthat/test-schema.R
- tests/testthat/test-tbl-sql.R
- tests/testthat/test-verb-compute.R
- tests/testthat/test-verb-copy-to.R
- tests/testthat/test-verb-joins.R
Closes #1151.
This PR adds
* `local_sqlite_connection()`
* `local_db_table()`
* `local_sqlite_con_with_aux()`
to get rid of the `on.exit()` calls in tests.
> Use `local_db_table()`

- NEWS.md
- R/backend-mysql.R
- tests/testthat/_snaps/backend-mysql.md
- tests/testthat/test-backend-mysql.R
> Fix `copy_inline()` for MariaDB

- R/db-io.R
- R/db-sql.R
- R/utils.R
- man/db-sql.Rd
They are pretty basic functions that so far didn't check their arguments at all
* `sql_table_index()`
* `sql_query_fields()`
* `sql_query_save()`
* `sql_query_wrap()`
* `sql_query_rows()`
* `sql_query_explain()`
* `db_copy_to()`
* `db_compute()`
* `db_write_table()`
> Add argument checks in some basic SQL functions

- NEWS.md
- R/backend-access.R
As noted in the issue and title, add != to <> translation for Access since that's what Access uses
> Add != to <> translation for Access (#1219)

- NEWS.md
- R/tbl-lazy.R
- man/tbl_lazy.Rd
- tests/testthat/_snaps/tbl-lazy.md
- tests/testthat/test-tbl-lazy.R
Closes #1208.
@hadley Or would you prefer first going to `deprecate_stop()`? I would have guessed `src` wasn't used much anymore that's why I removed it directly.
> Remove arg `src` from `tbl_lazy()`

- NEWS.md
- R/backend-.R
- man/arrange.tbl_lazy.Rd
- man/count.tbl_lazy.Rd
- man/distinct.tbl_lazy.Rd
- man/filter.tbl_lazy.Rd
- man/group_by.tbl_lazy.Rd
- man/mutate.tbl_lazy.Rd
- man/pull.tbl_sql.Rd
- man/select.tbl_lazy.Rd
- man/summarise.tbl_lazy.Rd
Using `x = row_number()` doesn't work but at least the argument name is the same.
> Fix interface of `ntile()`

- NEWS.md
- R/tidyeval-across.R
- tests/testthat/test-tidyeval-across.R
> Support namespaced functions in `across()`

- R/lazy-ops.R
- R/remote.R
This makes it much easier to test whether the SQL query generations works with `in_schema()` and `in_catalog()`. Before we always needed a live database to test support of schemas.
> Support `in_schema/catalog()` in `lazy_frame()`

- R/backend-mysql.R
- R/db-sql.R
- R/lazy-join-query.R
- R/query-join.R
- man/db-sql.Rd
- man/sql_build.Rd
- tests/testthat/test-verb-joins.R
Some time ago we added the feature to use `*` for column selection where possible. For select queries this was done in `sql_build()`, for join queries in `sql_render()`. This is inconsistent and I think it makes more sense to do this in `sql_build()`. This also has the advantage that it makes `sql_render()` a bit simpler for joins.
In the end this makes it easier to implement #1146 (this allows the user to control whether to use `*` or write out all columns).
> Generate `SELECT` sql for joins in `sql_build()`

- NEWS.md
- R/db.R
- R/explain.R
- R/lazy-join-query.R
- R/lazy-select-query.R
- R/lazy-set-op-query.R
- R/query-join.R
- R/remote.R
- R/sql-build.R
- R/verb-copy-to.R
- man/db-misc.Rd
- man/remote_name.Rd
- man/sql_build.Rd
- tests/testthat/test-query-join.R
- tests/testthat/test-translate-sql-window.R
- tests/testthat/test-verb-joins.R
- tests/testthat/test-verb-mutate.R
Part of #1146.
``` r
lf1 <- lazy_frame(x = 1, y = 2, z = 2, .name = "df1")
lf2 <- lazy_frame(x = 1, a = 2, b = 2, .name = "df2")
left_join_lf <- left_join(lf1, lf2, by = "x")
left_join_lf %>% show_query(use_star = TRUE)
#> <SQL>
#> SELECT `df1`.*, `a`, `b`
#> FROM `df1`
#> LEFT JOIN `df2`
#>   ON (`df1`.`x` = `df2`.`x`)
left_join_lf %>% show_query(use_star = FALSE)
#> <SQL>
#> SELECT `df1`.`x` AS `x`, `y`, `z`, `a`, `b`
#> FROM `df1`
#> LEFT JOIN `df2`
#>   ON (`df1`.`x` = `df2`.`x`)
right_join_lf <- right_join(lf1, lf2, by = "x") %>% select(x, a, b, y, z)
right_join_lf %>% show_query(use_star = TRUE)
#> <SQL>
#> SELECT `df2`.*, `y`, `z`
#> FROM `df1`
#> RIGHT JOIN `df2`
#>   ON (`df1`.`x` = `df2`.`x`)
right_join_lf %>% show_query(use_star = FALSE)
#> <SQL>
#> SELECT `df2`.`x` AS `x`, …
```
> Add argument `use_star`

- NEWS.md
- R/utils.R
- R/verb-joins.R
- man/join.tbl_sql.Rd
- tests/testthat/_snaps/verb-joins.md
- tests/testthat/test-verb-joins.R
Fix for #1305 
This follows the same conventions as the `multiple` and `unmatched` parameters, in that it supports the database default behaviour (allow many-to-many).
If the user attempts to provide a value for `relationship` other than `NULL` or `many-to-many`, an error will be thrown.
> Support relationship in joins

- R/tbl-lazy.R
- R/tidyeval-across.R
- R/verb-distinct.R
- R/verb-mutate.R
- R/verb-pivot-longer.R
- R/verb-pivot-wider.R
- tests/testthat/_snaps/tbl-lazy.md
- tests/testthat/test-tbl-lazy.R
- tests/testthat/test-verb-count.R
- tests/testthat/test-verb-pivot-wider.R
Helps towards #1056.
Simply using `inform()` in `names.tbl_lazy()` is quite annoying. An assignment, e.g.
```
lf <- lazy_frame(x = 1)
```
inside RStudio triggers the `names()` function and therefore the user is informed. So, this should only inform under certain conditions.
> Don't rely on `names()` for `tbl_lazy()`

- NEWS.md
- R/backend-snowflake.R
- tests/testthat/_snaps/backend-snowflake.md
- tests/testthat/test-backend-snowflake.R
Closes #1329 
Incremental approaches taken (as of commits linked below):
1. Initial approach taken from https://stackoverflow.com/a/74529349/22193215, but that doesn't scale well to dates, only integers / floats, since NEGATE on a date isn't supported for the `pmin(..., na.rm = TRUE)` translation: c2532c055f629a1f142e7490bf5f759d129c98bd
2. Migrated to approach closer to https://github.com/tidyverse/dbplyr/blob/main/R/backend-access.R#L135-L142: only supports two columns: 773633110c05b4bc2e3974e6fd360c1b996c2c56
3. [current] generalizable approach for N>2 columns, using ugly, but recursive approach: 1ac318808e8d78e684b32c963a10b61579ef5710
> Respect na.rm = TRUE in `pmin()` and `pmax()` for Snowflake

- R/sql-expr.R
- R/translate-sql-window.R
- tests/testthat/test-sql-expr.R
Where `is.atomic(NULL)` will return `FALSE`
> Prepare for upcoming R-devel change

- NEWS.md
- R/backend-.R
- R/backend-redshift.R
- tests/testthat/test-backend-.R
> Coerce n to integer in lead too

- NEWS.md
- R/backend-snowflake.R
- tests/testthat/_snaps/backend-snowflake.md
- tests/testthat/test-backend-snowflake.R
* Added support for str_starts() and str_ends() by using Snowflake's REGEXP_INSTR() function
* Refactored str_detect() to use Snowflake's CONTAINS() function instead of hacking with REGEXP() which anchors the start and end by default
Satisfies #1405
> Better support for string matching in Snowflake

- R/tbl-sql.R
> Don't check `...` in `tbl_sql()`

- NEWS.md
- R/translate-sql-helpers.R
- tests/testthat/test-backend-.R
- tests/testthat/test-translate-sql-helpers.R
> Unary minus doesn't need parens for simple expressions

- NEWS.md
- R/tidyeval.R
- R/translate-sql.R
- tests/testthat/_snaps/translate-sql.md
- tests/testthat/test-tidyeval.R
- tests/testthat/test-translate-sql.R
I'm not sure how this broke, but the code for handling this already exists in `translate_sql()`, so I'm not sure why we started doing some `::` handling in `partial_eval()`.
Fixes #1426
> Translations for namespaced functions must exist

- R/db-sql.R
- R/ident.R
- R/schema.R
- R/src_dbi.R
- R/verb-copy-to.R
- _pkgdown.yml
- man/copy_to.src_sql.Rd
- man/ident.Rd
- man/in_schema.Rd
- man/sql_query_insert.Rd
- man/tbl.src_dbi.Rd
> Steer people towards I()

- R/backend-mssql.R
- R/backend-oracle.R
- R/backend-postgres.R
- R/backend-redshift.R
- R/backend-snowflake.R
- R/backend-spark-sql.R
- tests/testthat/test-backend-mssql.R
- tests/testthat/test-backend-redshift.R
- tests/testthat/test-backend-snowflake.R
> Fix R CMD check NOTEs

- NEWS.md
- R/verb-select.R
- tests/testthat/_snaps/verb-select.md
- tests/testthat/test-verb-select.R
Fixes #1437
This will stop `arrange`d computed columns from being inlined away from subqueries. Of course the subquery `ORDER BY` warning will be thrown, but I think that is expected behavior.
Before:
``` r
library(dplyr, warn.conflicts = FALSE)
db <- lazy_frame(x = 1, y = 2) 
db %>% 
mutate(z = 1) %>% 
arrange(x, z) %>%
select(x)
#> <SQL>
#> SELECT `x`
#> FROM `df`
#> ORDER BY `x`, `z`
```
<sup>Created on 2024-02-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
After:
``` r
library(dplyr, warn.conflicts = FALSE)
db <- lazy_frame(x = 1, y = 2) 
db %>% 
mutate(z = 1) %>% 
arrange(x, z) %>%
select(x)
#> Warning: ORDER BY is ignored in subqueries without LIMIT
#> ℹ Do you need to move arrange() later in the pipeline or use window_order() instead?
#> …
```
> Refine `select` inline criteria to keep `arrange`d computed columns

- NEWS.md
- R/lazy-select-query.R
- tests/testthat/_snaps/verb-joins.md
- tests/testthat/test-verb-joins.R
> Keep filtered aggregates with subsequent select in semi_join

- NEWS.md
- R/verb-summarise.R
- tests/testthat/_snaps/tbl-sql.md
- tests/testthat/_snaps/verb-summarise.md
- tests/testthat/test-tbl-sql.R
- tests/testthat/test-verb-summarise.R
> Fix `across()` in combination with `summarise(.by)`

- R/backend-spark-sql.R
Fix for https://github.com/tidyverse/dbplyr/issues/1502
Previously this example would fail, it now succeeds:
```r
results <- tbl(con, I("samples.nyctaxi.trips")) %>%
group_by(pickup_zip) %>%
summarise(avg_trip_dist = mean(trip_distance)) %>%
compute(
name = I("zacdav.default.avg_trip_dist"),
temporary = FALSE,
overwrite = TRUE
)
```
> Allowing `compute` to persist tables with Spark SQL backend

- NEWS.md
- R/backend-spark-sql.R
Adding notes that were omitted as part of https://github.com/tidyverse/dbplyr/pull/1514
> `NEWS.md` notes for #1502/#1514 - SparkSQL backend `compute` changes

- NEWS.md
- R/backend-mssql.R
- R/backend-postgres.R
- R/backend-redshift.R
- R/backend-snowflake.R
- tests/testthat/test-backend-mssql.R
- tests/testthat/test-backend-postgres.R
- tests/testthat/test-backend-redshift.R
- tests/testthat/test-backend-snowflake.R
> fix for difftime

- NEWS.md
- R/backend-mssql.R
- R/backend-postgres.R
- R/backend-redshift.R
- R/backend-snowflake.R
- R/backend-spark-sql.R
- tests/testthat/test-backend-mssql.R
- tests/testthat/test-backend-postgres.R
- tests/testthat/test-backend-redshift.R
- tests/testthat/test-backend-snowflake.R
- tests/testthat/test-backend-spark-sql.R
For #1495, adds translations for clock::date_count_between() for a number of backends along with tests and update of news.
> date_count_between translations

- NEWS.md
- R/backend-spark-sql.R
- tests/testthat/test-backend-spark-sql.R
> Fix add_years translation on spark

- vignettes/translation-function.Rmd
I hope all these changes are correct and acceptable.
One change I didn't make because I wasn't sure: on the current line 52, the comment says "In SQLite variable names are escaped by double quotes:", but the printed output shows single back-quotes instead (`` rather than "") ... ??
> various small translate-sql vignette corrections

- R/utils-check.R
- tests/testthat/_snaps/backend-snowflake.md
- tests/testthat/_snaps/rows.md
- tests/testthat/_snaps/translate-sql-conditional.md
- tests/testthat/_snaps/verb-pivot-wider.md
- tests/testthat/test-backend-snowflake.R
Related to the first checkbox in #1546 but does not close; a demo of what that PR would look like for all backends.
For snowflake, transition `expect_error()`:
* ...to snapshot when testing the error message
* ...to classed error when testing an error from another package or an error thrown from a widely-used helper
* ...to `expect_no_error()` (or no test) when `regex = NA`
* Analogous story for `expect_warning()` and `expect_message()`.
> transition `expect_error()` for snowflake backend

- R/translate-sql-helpers.R
- tests/testthat/_snaps/backend-.md
- tests/testthat/_snaps/backend-access.md
- tests/testthat/_snaps/backend-mssql.md
- tests/testthat/_snaps/backend-oracle.md
- tests/testthat/_snaps/backend-postgres.md
- tests/testthat/_snaps/backend-redshift.md
- tests/testthat/_snaps/backend-spark-sql.md
- tests/testthat/_snaps/backend-sqlite.md
- tests/testthat/_snaps/translate-sql-helpers.md
- tests/testthat/test-backend-.R
- tests/testthat/test-backend-access.R
- tests/testthat/test-backend-mssql.R
- tests/testthat/test-backend-oracle.R
- tests/testthat/test-backend-postgres.R
- tests/testthat/test-backend-redshift.R
- tests/testthat/test-backend-spark-sql.R
- tests/testthat/test-backend-sqlite.R
- tests/testthat/test-translate-sql-helpers.R
Closes #1552. Following the lead of #1547, audits calls to `expect_error()`.
Transition `expect_error()`:
* ...to snapshot when testing the error message
* ...to classed error when testing an error from another package or an error thrown from a widely-used helper
* ...to `expect_no_error()` when `regex = NA`
> audit calls to `expect_error()` for `backend-*.R` files

- NEWS.md
- R/backend-snowflake.R
- tests/testthat/_snaps/backend-snowflake.md
- tests/testthat/test-backend-snowflake.R
Related to #1546 but doesn't close. Speccing out the changes in `backend-snowflake.R` that would be applied for each backend to address the "use type checkers" bullet in the linked issue.
My sense here is that we ought not to be checking arguments that are injected via `!!` straight into `translate_sql()` or `sql_expr()`?
> use type checkers in `backend-snowflake.R`

- NEWS.md
- R/backend-.R
- R/backend-hive.R
- R/backend-mssql.R
- R/backend-postgres.R
- R/backend-redshift.R
- R/backend-spark-sql.R
- R/backend-teradata.R
- R/utils.R
- tests/testthat/_snaps/backend-mssql.md
- tests/testthat/_snaps/backend-postgres.md
- tests/testthat/_snaps/backend-redshift.md
- tests/testthat/_snaps/backend-spark-sql.md
Closes #1555. As in #1554, didn't apply checks to arguments that are passed directly to `sql_*()` functions.
> use type checkers in `backend-*.R` files

- DESCRIPTION
- tests/testthat/_snaps/backend-sqlite.md
Closes #1562. We'll still see some unrelated postgres GHA failures on this PR.
We [first saw this failure on 11/20](https://github.com/tidyverse/dbplyr/actions/runs/11956788170/job/33332369654?pr=1558), 3 days after [RSQLite 2.3.8 was released on 11/17](https://github.com/r-dbi/RSQLite/blob/7a0dd64c0378d167e9203c379344bbf3fdf2dd83/NEWS.md#rsqlite-238-2024-11-17). If I downgrade with `pak::pak("r-dbi/RSQLite@v2.3.7")`, I see the snap change this PR proposes reverted:
```
> pak::pak("r-dbi/RSQLite@v2.3.7")
→ Will update 1 package.
→ The package (0 B) is cached.
+ RSQLite 2.3.8 → 2.3.7 👷🏼🔧 (GitHub: 7588a97)
! RSQLite is loaded in the current R session, you probably need to
restart R after the installation.
? Do you want to continue (Y/n) Y
ℹ No downloads are needed, 1 pkg is cached
✔ Got …
```
> update SQLite snap
